# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from __future__ import annotations

from os import PathLike
from typing import Any, Optional, Union

import numpy as np
import numpy.typing as npt

Key = Union[str, int, bytes]
_F32Array = npt.NDArray[np.float32]
_F32Matrix = npt.NDArray[np.float32]

def format_version() -> str: ...

class ValiseError(Exception): ...
class CorruptionError(ValiseError): ...
class BusyError(ValiseError): ...
class UnsupportedError(ValiseError): ...
class ValidationError(ValiseError): ...
class NotCalibratedError(ValiseError): ...
class SchemaMismatchError(ValiseError): ...

class Space:
    @property
    def name(self) -> str: ...
    @property
    def is_text(self) -> bool: ...
    @property
    def is_vector(self) -> bool: ...

class Schema:
    def __init__(self) -> None: ...
    def text(
        self,
        name: str,
        lang: Optional[str] = ...,
        space: Optional[Space] = ...,
    ) -> None: ...
    def vector(
        self,
        name: str,
        dim: Optional[int] = ...,
        space: Optional[Space] = ...,
        metric: Optional[str] = ...,
        codec_family: Optional[str] = ...,
        qam_amp_bits: Optional[int] = ...,
        qam_phase_bits: Optional[int] = ...,
        upq_cells: Optional[int] = ...,
        upq_design: Optional[str] = ...,
        cal_mode: Optional[str] = ...,
        cal_sample: Optional[int] = ...,
        cal_vectors: Optional[_F32Matrix] = ...,
    ) -> None: ...

class Record:
    def __init__(self) -> None: ...
    def text(self, field: str, value: str) -> "Record": ...
    def vector(self, field: str, values: _F32Array) -> "Record": ...
    def at(self, unix_secs: int) -> "Record": ...
    def child_of(self, parent: Key) -> "Record": ...

class Search:
    def __init__(self) -> None: ...
    def text(
        self,
        field: str,
        query: str,
        scorer: str = ...,
        k1: Optional[float] = ...,
        b: Optional[float] = ...,
        tf_mode: Optional[str] = ...,
    ) -> "Search": ...
    def vector(self, field: str, query: _F32Array, rerank: str = ...) -> "Search": ...
    def fuse_rrf(self, k: Optional[int] = ...) -> "Search": ...
    def fuse_weighted(self, text: float, vector: float) -> "Search": ...
    def recency_range(self, from_: int, to: int) -> "Search": ...
    def recency_half_life(self, days: float) -> "Search": ...
    def recency_rrf_channel(self, half_life_days: float, weight: float) -> "Search": ...
    def top_k(self, k: int) -> "Search": ...
    def now(self, unix_secs: int) -> "Search": ...

class Stored:
    key: Key
    collection: str
    created_at: int
    text: Optional[str]
    vectors: list[tuple[str, _F32Array]]

class View:
    def collections(self) -> list[str]: ...

class Partitioned:
    def view_last_days(self, days: int, now: Optional[int] = ...) -> View: ...
    def view_range(self, from_: int, to: int) -> View: ...
    def view_partitions(self, suffixes: list[str]) -> View: ...
    def all(self) -> View: ...
    def forget_before(self, cutoff: int) -> int: ...

class Reader:
    def get(self, coll: str, key: Key) -> Optional[Stored]: ...
    def get_many(self, coll: str, keys: list[Key]) -> list[Optional[Stored]]: ...
    def search(self, coll: str, search: Search) -> tuple[list[Key], _F32Array]: ...
    def search_view(
        self, view: View, search: Search
    ) -> tuple[list[Key], _F32Array, list[str]]: ...

class Writer:
    def put(self, coll: str, key: Key, record: Record) -> None: ...
    def put_auto(self, coll: str, record: Record) -> Key: ...
    def put_into(self, partitioned: Partitioned, key: Key, record: Record) -> None: ...
    def put_many(
        self,
        coll: str,
        keys: list[Key],
        vectors: _F32Matrix,
        field: str = ...,
        texts: Optional[list[str]] = ...,
        text_field: str = ...,
    ) -> None: ...
    def delete(self, coll: str, key: Key) -> bool: ...
    def commit(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> "Writer": ...
    def __exit__(self, *args: Any) -> bool: ...

class Store:
    @staticmethod
    def open(path: Union[str, PathLike[str]], durability: str = ...) -> "Store": ...
    @staticmethod
    def create(path: Union[str, PathLike[str]], durability: str = ...) -> "Store": ...
    def collection(self, name: str, schema: Schema) -> None: ...
    def define_space_text(self, name: str, lang: Optional[str] = ...) -> Space: ...
    def define_space_vector(
        self,
        name: str,
        dim: int,
        metric: Optional[str] = ...,
        codec_family: Optional[str] = ...,
        qam_amp_bits: Optional[int] = ...,
        qam_phase_bits: Optional[int] = ...,
        upq_cells: Optional[int] = ...,
        upq_design: Optional[str] = ...,
        cal_mode: Optional[str] = ...,
        cal_sample: Optional[int] = ...,
        cal_vectors: Optional[_F32Matrix] = ...,
    ) -> Space: ...
    def space(self, name: str) -> Optional[Space]: ...
    def spaces(self) -> list[tuple[str, Optional[int], bool]]: ...
    def collections(self) -> list[tuple[str, int]]: ...
    def partitioned(self, base: str, schema: Schema, by: str) -> Partitioned: ...
    def reader(self) -> Reader: ...
    def writer(self) -> Writer: ...
    def get(self, coll: str, key: Key) -> Optional[Stored]: ...
    def search(self, coll: str, search: Search) -> tuple[list[Key], _F32Array]: ...
    def search_view(
        self, view: View, search: Search
    ) -> tuple[list[Key], _F32Array, list[str]]: ...
    def compact(self, recalibrate: bool = ...) -> dict[str, Any]: ...
    def stats(self) -> dict[str, Any]: ...
